apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recipe-share

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: recipe-share
  app.kubernetes.io/part-of: recipe-share
